# Generated by Django 6.1 on 2026-08-24 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='lat_name',
            new_name='last_name',
        ),
    ]
