# Generated by Django 6.1 on 2026-08-31 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
